#!/bin/sh

# git will set these environment variables, when running post-receive, to non-
# default values. We unset them to get normal bash behaviour below
unset GIT_DIR
unset GIT_WORK_TREE

cd /home/ubuntu/checkout
git fetch
git reset --hard origin/master
npm install
#should "forever restart" instead of relying at forever watching for file changes
cd -
