#!/bin/sh

# git will set these environment variables, when running post-receive, to non-
# default values. We unset them to get normal bash behaviour below
unset GIT_DIR
unset GIT_WORK_TREE

cd /home/ubuntu/checkout
# get latest code
git fetch
git reset --hard origin/master
# install dependencies
npm install
# restart node process
sudo forever restart app.js
cd -
